---
- name: Grant/revoke access to the group of servers to the new developer
  hosts: all
  become: true
  vars:
    developers_group: 'dev_group'
	developers_list:
	# Add users to the servers group
  - name: "new developer"
    username: "newdev"
    keys:
      active:
        - "ssh-rsa newdev@abc.io
    shell: "/bin/bash"
    state: present
    # Revoke ssh access from the server group
  - name: "Revoke user from the group"
    username: "olddev
    state: absent
	
  tasks:

  - name: Setup the new user
    user:
      name: "{{ item.username }}"
      state: "{{ item.state | default('present') }}"
      shell: "{{ item.shell | default('/bin/bash') }}"
      group: "{{ dev_group }}"
      remove: yes
    when: item.username is defined
    with_items:
      - "{{ all_developers_list }}"

  - name: Add SSH-keys to users
    authorized_key:
      user: "{{ item.0.username }}"
      key: "{{ item.1 }}"
    with_subelements:
      - "{{ all_developers_list }}"
      - keys.active
      - flags:
        skip_missing: True
    when: item.0.state != "absent"

  - name: Remove old SSH-keys from users
    authorized_key:
      user: "{{ item.0.username }}"
      key: "{{ item.1 }}"
      state: absent
    with_subelements:
      - "{{ all_developers_list }}"
      - keys.disabled
      - flags:
        skip_missing: True
    when: item.0.state != "absent"
